name: Build
on: [push, pull_request]

jobs:
  build:
    name: Test Fluffy (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:

    - name: Git checkout
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install

    - name: Test with pytest
      run: |
        pip install pytest
        pytest -rxs tests/